# Julia 的基本数据和相应运算

## 整数与浮点数

Julia

程序中的整数值可以直接写成如 123 或者 -123 这样。 虽然整数有多种类型， ⼀般程序中不必特别关⼼整数常量的具体类型。 Julia 允许使⽤特别⻓的整数， 这时其类型为BigInt。 Julia 的浮点数可以写成带点的形式如 123.0 , 1.23 , 也可以写成带有10 的幂次如 1.23e3 (表示 ), 1.23e-3 ( 表示 ) 。 这些写法都属于

1.23 × 103 

1.23 × 10−3 

Float64

类型的浮点数。Julia 还有其他类型的浮点数，但是科学计算中主要使⽤Float64类型， 在别的语⾔中这称为双精度浮点数。 Julia 还提供了任意精度整数与任意精度浮点数。 布尔类型Bool 只有两个值：true 和false 。

# 四则运算
表示加、减、乘、除、乘⽅的运算符分别为：

+

- *

/

^

浮点数的四则运算遵循传统的算数运算规则和优先级规定。 ⽤圆括号改变优先级。如

In [1]:
(1.3+2.5)*2.0 - 3.6/1.2 + 1.2^2

6.039999999999999

表示 
$$(1.3+2.5)*2.0 -3.6/1.2 + 1.2^2$$
注意浮点运算引起会造成数值计算误差。

# 整数的四则运算
整数加法、减法、乘法结果仍为整数， 这样因为整数的表示范围有限，有可能发⽣溢出。 如

In [2]:
10 + 2*3 - 3*4

4

整数⽤“/” 作的除法总是返回浮点数，即使结果是整数也是⼀样：

In [3]:
10/2

5.0

求整数除法的商，⽤ ÷ 运算符 , 如

In [4]:
5÷3

1

其中 ÷ 的输⼊⽅法是在命令⾏中输⼊ \div 后按TAB 键。 这种⽅法可以输⼊许多数学符号， 如 α (alpha) ， π (pi) ， ∑ (sum) ，等等。

整数⽤ a % b 表示a 整除b 的余数，结果符号总是取a 的符号。如

In [5]:
10 % 3

1

In [6]:
# \div
10 ÷ 3 

3

In [7]:
# \pi
π

π = 3.1415926535897...

In [8]:
# \alpha = 1
# \beta = 2
# \alpha + \beta
α = 1
β = 2
α + β

3

整数与浮点数的混合运算会将整数转换成浮点数再计算。
# 数学函数
和其它科学计算语⾔类似， Julia 也⽀持常⻅的数学函数， 如 log , exp , sqrt , sin , cos , tan 等。 round(x) 将 x 四舍五⼊为整数， round(x, digits=2) 将 x 四舍五⼊到两位⼩数。 floor(x) 求⼩于等于 x 的最⼤整数， ceil(x) 求⼤于等于 x 的最

# 字符串
单个字符在两边⽤单撇号界定，如 'A' ，AbstractChar ' 囧 ' 。 字符都是⽤Unicode 编码存储，具体使⽤UTF-8 编码。 每个字符可能使⽤1 到4 个字节表示。 字符的类型为 Char， ⾃定义函数中的字符参数可声明为 。 零到多个字符组成字符串， 程序中的字符串在两边⽤双撇号界定，如 "A cat" ， " 泰囧 " 。 字符串数据类型名称为String ， ⾃定义函数中的字符串参数可声明为 AbstractString。

对于占据多⾏的字符串， 可以在两侧分别⽤三个双撇号界定。如

In [9]:
"""
这是第⼀⾏ 
这是第⼆⾏ 
三个双撇号界定的字符串中间的单个双撇号"不需要转义
"""

"这是第⼀⾏ \n这是第⼆⾏ \n三个双撇号界定的字符串中间的单个双撇号\"不需要转义\n"

注意多⾏内容的⾸⾏不需要紧挨着写在开头的三个双撇号后⾯同⼀⾏内。 
字符串属于不可修改类型(immutable) ， 即不能直接修改字符串的内容， 但可以给保存了字符串的变量赋值为⼀个新的字符串。 
⽤星号 “ * ” 连接两个字符串，也可以将字符连接成字符串，如

In [10]:
'#' * "这是"*"美好的⼀天" * "。" 

"#这是美好的⼀天。"

# 变量
变量名是⼀个标识符， ⽤来指向某个值在计算机内存中的存储位置。 变量名可以⽤英⽂⼤⼩写字⺟、下划线、数字、允许的Unicode 字符， 区分⼤⼩写。 变量名不 允许使⽤空格、句点以及其它标点符号和井号之类的特殊字符。 为兼容性起⻅，尽可能不要⽤汉字作为变量名。 变量名主要使⽤⼩写字⺟、数字和下划线构成， 两个英⽂单词之间可以⽤下划线连接， 如 total_number ， 也 可以在单词之间使⽤开头字⺟⼤写来区分单词， 如 totalNumber ， 第⼀个单词仍全部⽤⼩写。

给变量赋值，即将变量名与⼀个内存中的内容联系起来，也称为绑定（binding ）， 使⽤等号“=” ，等号左边写变量名，右边写要保存到变量中的值。如

In [11]:
x = 123

123

In [12]:
y = 1+3/2

2.5

In [13]:
addr10086 = "北京市海淀区颐和园路5号"

"北京市海淀区颐和园路5号"

变量的类型是由它保存的（指向的内存中的）值的类型决定的， 不需要说明变量类型（Julia 允许说明变量类型，但⼀般不需要）。 变量赋值后，就可以参与运算，如：

In [14]:
x = 123

y = 1+3/2

x + y*2

128.0

变量名前⾯紧挨着数字表示相乘，如

In [15]:
x + 2y

128.0

赋值还有⼀种计算修改简写⽅式， 即将变量值进⾏四则运算后保存回原变量， 格式为 x op= expr ， 其中 op 是某种四则运算， 这等价于 x = x op expr

In [16]:
x = 123

x += 100
x

223

# ⽐较和逻辑运算
## ⽐较运算
两个数值之间⽤如下的⽐较运算符进⾏⽐较：

==

!=

<

<=

> >=

分别表示等于、不等于、⼩于、⼩于等于、⼤于、⼤于等于。 要特别注意“ 等于” ⽐较⽤两个等号表示。 ⽐较的结果是true( 真值) 或者false( 假值) 。 结果类型为布尔型（Bool ）。 如

In [17]:
1 == 1.0

true

In [18]:
2 != 2.0001

true

In [19]:
3.5 > -1

true

In [20]:
3.5 < -1.5

false

In [21]:
-3.5 >= 1.2

false

In [22]:
-3.5 <= 1.2

true

两个字符串之间也可以⽐较， ⽐较时按字典序⽐较， 两个字符的次序按照其Unicode 编码值⽐较。如

In [23]:
"abc" == "ABC"

false

In [24]:
"ac" < "ab"

false

In [25]:
"abc" < "abb"

false

In [26]:
"abc" > "abb"

true

In [27]:
"陕⻄省" == "⼭⻄省"

false

## 逻辑运算
⽐较通常有变量参与。如

In [28]:
age = 35; sex = "F"
age < 18

false

In [29]:
sex == "F"

true

有时需要构造复合的条件， 如“ 年龄不⾜18 岁且性别为⼥” ， “ 年龄在18 岁以上或者性别为男” 等。 

⽤ && 表示要求两个条件同时成⽴， ⽤ || 表示只要两个条件之⼀成⽴则结果为真， ⽤ !cond 表示 cond 的反⾯。 如

In [30]:
age < 18 && sex == "F"

false

In [31]:
age >= 18 || sex == "M"

true

# 简单的输出
在Julia 命令⾏，键⼊变量名或者计算表达式直接在下⾯显示结果。 可以⽤ println() 函数显示指定的变量和结果。如

In [32]:
println(x+y*2)

228.0


在 println() 中多个要输出的项⽤逗号分开。 两项之间没有默认的分隔， 如果需要分隔可以⾃⼰写在输出项中。

In [33]:
println("x=", x, " y=", y, " x + y*2 =", x+y*2)

x=223 y=2.5 x + y*2 =228.0


println()函数输出会将后续输出设置到下⼀⾏， ⽽ print() 函数与 println() 类似但是将后续输出设置在当前⾏。


在命令⾏运⾏时， 表达式的值⾃动显示。 在表达式末尾⽤分号结尾表示不要显示该表达式的结果。

在⽤ include() 命令执⾏整个脚本⽂件时， 每个表达式的结果默认不⾃动显示。 

字符串中可以⽤ $ 变量名 或 $( 表达式 ) 的格式插⼊变量或表达式的值。例如

In [34]:
name = "John"; "My name is $name"

"My name is John"

In [35]:
"100$(name)999"

"100John999"

# 向量
Julia 的向量实际是⼀维数组。 在程序中直接定义⼀个向量， 只要⽤⽅括号内写多个逗号分隔的数值，如

In [36]:
v1 = [1, 3, 4, 9, 13]

5-element Array{Int64,1}:
  1
  3
  4
  9
 13

In [37]:
v2 = [1.5, 3, 4, 9.12]

4-element Array{Float64,1}:
 1.5
 3.0
 4.0
 9.12

其中v1 是整数型的向量， v2 是浮点型Float64 的向量。

⽤ length(x) 求向量 x 的元素个数，如

In [38]:
length(v1)

5

可以⽤ 1:5 定义⼀个范围， 在仅使⽤其中的元素值⽽不改写时作⽤与 [1, 2, 3, 4, 5] 类似。 

1:2:9 定义带有步⻓的范围，表示的值与 [1, 3, 5, 7, 9] 类似。 

范围只需要存储必要的开始、结束、步⻓信息， 所以更节省空间， 但是不能对其元素进⾏修改。

In [39]:
1:5

1:5

In [40]:
1:2:9

1:2:9

范围不是向量，⽤ collect() 函数可以将范围转换成向量，如：

In [41]:
collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [42]:
collect(1:2:9)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

# 向量下标
若 x 是向量， i 是正整数， x[i] 表示向量的第 i 个元素。 第⼀个元素的下标为1 ，这种规定与R 、FORTRAN 语⾔相同， 但不同于Python 、C 、C++ 、JAVA 语 ⾔。 如

In [43]:
v1[2]

3

⽤ end 表示最后⼀个元素位置，如：

In [44]:
v1[end]

13

对元素赋值将在原地修改元素的值，如

v1[2] = -999; v1

⽤范围作为下标

下标可以是⼀个范围，如

In [45]:
v1[2:4]

3-element Array{Int64,1}:
 3
 4
 9

在这种范围中，⽤ end 表示最后⼀个下标，如

In [46]:
v1[4:end]

2-element Array{Int64,1}:
  9
 13

In [47]:
v1[1:end-1]

4-element Array{Int64,1}:
 1
 3
 4
 9

数组作为下标

向量的下标也可以是⼀个下标数组，如

In [48]:
v1[[1, 3, 5]]

3-element Array{Int64,1}:
  1
  4
 13

取出的多个元素可以修改，可以⽤ .= 运算符赋值为同⼀个标量，如：

In [49]:
v1[1:3] .= 0; v1

5-element Array{Int64,1}:
  0
  0
  0
  9
 13

也可以分别赋值，如

In [50]:
v1[[1, 3, 5]] = [101, 303, 505]; v1

5-element Array{Int64,1}:
 101
   0
 303
   9
 505

# 向量与标量的运算
向量与⼀个标量作四则运算， 将运算符前⾯加句点“.” ： .+ .- .* ./ .^ 表示向量的每个元素分别与该标量作四则运算， 结果仍是向量。如

In [51]:
v1 = [1, 3, 4, 9, 13]

v1 .+ 100

5-element Array{Int64,1}:
 101
 103
 104
 109
 113

In [52]:
100 .- v1

5-element Array{Int64,1}:
 99
 97
 96
 91
 87

In [53]:
v1 .* 2

5-element Array{Int64,1}:
  2
  6
  8
 18
 26

In [54]:
v1 ./ 10

5-element Array{Float64,1}:
 0.1
 0.3
 0.4
 0.9
 1.3

In [55]:
v1 .^ 2

5-element Array{Int64,1}:
   1
   9
  16
  81
 169

# 向量与向量的四则运算
两个等⻓的向量之间作加点的四则运算，表示对应元素作相应的运算。如

In [56]:
v1 = [1, 3, 4, 9, 1]

v3 = [2, 5, 6, 7, 10]

v1 .+ v3

5-element Array{Int64,1}:
  3
  8
 10
 16
 11

向量加减法也可以⽤不加点的运算符，但对应元素间乘除必须⽤加点的“.*” 和“./” ：

In [57]:
v1 + v3

5-element Array{Int64,1}:
  3
  8
 10
 16
 11

In [58]:
v1 .+ v3

5-element Array{Int64,1}:
  3
  8
 10
 16
 11

In [59]:
v1 .- v3

5-element Array{Int64,1}:
 -1
 -2
 -2
  2
 -9

In [60]:
v1 .* v3

5-element Array{Int64,1}:
  2
 15
 24
 63
 10

In [61]:
v1 ./ v3

5-element Array{Float64,1}:
 0.5
 0.6
 0.6666666666666666
 1.2857142857142858
 0.1

# 向量的⽐较运算

两个标量之间可以进⾏如下的⽐较运算： == !== < <= > >= 向量每个元素与标量之间、两个向量对应元素之间⽐较， 只要在前⾯的⽐较运算符前⾯增加句点：

.==

.!=

.<

.<=

.>

.>=

标量⽐较结果之间可以⽤ && 表示“ 同时成⽴ ”, || 表示“ ⾄少其中之⼀成⽴” 。 布尔型标量与向量、向量之间可以⽤ .& 表示元素间“ 与” ， .| 表示元素间“ 或” 。

# 向量初始化
⽤ zeros(n) 可以⽣成元素类型为Float64 、元素值为0 、⻓度为n 的向量，如

In [62]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

⽤ zeros(Int64, 3) 可以⽣成指定类型的（这⾥是Int64 ）初始化向量。如

In [63]:
zeros(Int64, 3)

3-element Array{Int64,1}:
 0
 0
 0

⽤ Vector{Float64}(undef, n) 可以⽣成元素类型为Float64 的⻓度为n 的向量， 元素值未初始化，如

In [64]:
 Vector{Float64}(undef, 3)

3-element Array{Float64,1}:
 2.220572551e-314
 2.220572583e-314
 2.2205725987e-314

类似可以⽣成其它元素类型的元素值未初始化向量，如

In [65]:
Vector{Int}(undef, 3)

3-element Array{Int64,1}:
 4494551504
 5003724304
 4494551568

⽤这样的办法为向量分配存储空间后可以随后再填⼊元素值。 

可以⽤ collect() 将⼀个范围转换成可修改的向量。